from django.test import TestCase
from .models import Patient, User, Consultation
from .serializers import ConsultationSerializer


class ConsultationSerializerTest(TestCase):
    def setUp(self):
        self.patient = Patient.objects.create(
            ghana_card_id="123",
            first_name="Jane",
            last_name="Doe",
            date_of_birth="1990-01-01",
            gender="F",
            phone="555-1234",
        )
        self.doctor = User.objects.create_user(
            username="drsmith",
            password="test",
            role="DOCTOR",
            first_name="John",
            last_name="Smith",
        )
        self.consultation = Consultation.objects.create(
            patient=self.patient,
            doctor=self.doctor,
            chief_complaint="Headache",
        )

    def test_patient_name_in_serializer(self):
        serializer = ConsultationSerializer(self.consultation)
        data = serializer.data
        self.assertEqual(data.get("patient_name"), "Jane Doe")
        # doctor_name should include prefix
        self.assertEqual(data.get("doctor_name"), "Dr. John Smith")

    def test_medical_fields_returned_from_record(self):
        # create a medical record that would normally be generated by the
        # serializer when saving a consultation
        MedicalRecord.objects.create(
            patient=self.patient,
            doctor=self.doctor,
            appointment=None,
            diagnosis="Flu",
            symptoms="Fever",
            notes="Rest",
            blood_pressure="120/80",
            temperature=37.2,
            allergies="Peanuts",
            chronic_conditions="Diabetes",
        )
        serializer = ConsultationSerializer(self.consultation)
        data = serializer.data
        self.assertEqual(data.get("diagnosis"), "Flu")
        self.assertEqual(data.get("allergies"), "Peanuts")
        self.assertEqual(data.get("temperature"), "37.2")


class PatientSummarySerializerTest(TestCase):
    def setUp(self):
        # patient with direct allergy data
        self.patient = Patient.objects.create(
            ghana_card_id="456",
            first_name="Sam",
            last_name="Taylor",
            date_of_birth="1985-05-05",
            gender="M",
            phone="555-5678",
            allergies="Pollen",
            chronic_conditions="Asthma",
        )

    def test_summary_from_patient_fields(self):
        serializer = PatientSummarySerializer(self.patient)
        data = serializer.data
        self.assertEqual(data.get("allergies"), "Pollen")
        self.assertEqual(data.get("chronic_conditions"), "Asthma")

    def test_summary_prefers_medical_record(self):
        # create a medical record with different values
        MedicalRecord.objects.create(
            patient=self.patient,
            doctor=self.patient,  # irrelevant
            appointment=None,
            diagnosis="",
            symptoms="",
            notes="",
            blood_pressure="",
            temperature=0,
            allergies="Penicillin",
            chronic_conditions="Diabetes",
        )
        serializer = PatientSummarySerializer(self.patient)
        data = serializer.data
        self.assertEqual(data.get("allergies"), "Penicillin")
        self.assertEqual(data.get("chronic_conditions"), "Diabetes")
