# Generated by Django 6.0.2 on 2026-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patient_allergies_patient_chronic_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
