# Generated by Django 6.0.2 on 2026-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_laborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('DOCTOR', 'Medical Doctor'), ('NURSE', 'Nursing Staff'), ('PHARMACIST', 'Pharmacist'), ('RECEPTIONIST', 'Front Desk/OPD'), ('LAB_TECH', 'Laboratory Technician'), ('RADIOLOGIST', 'Radiologist')], default='RECEPTIONIST', max_length=20),
        ),
    ]
