# Generated by Django 6.0.2 on 2026-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auditlog_delete_vitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(default='Korle Bu Teaching Hospital', max_length=255)),
                ('facility_code', models.CharField(default='KBTH-001', max_length=50)),
                ('contact_phone', models.CharField(default='+233 302 665 401', max_length=20)),
                ('email', models.EmailField(default='info@kbth.gov.gh', max_length=254)),
                ('region', models.CharField(default='greater-accra', max_length=100)),
                ('session_timeout', models.IntegerField(default=30)),
                ('audit_logging', models.BooleanField(default=True)),
            ],
        ),
    ]
