# Generated by Django 6.0.2 on 2026-03-06 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_hospitalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='laborder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_TAKEN', 'Sample Taken'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
